### ISSUE TITLE
不可以下载比较小的安装包？？？？

### ISSUE THREAD

**Issue by strootree** [itsnows/android-upgrade#1]

**Comment by itsnows** [comment]
可以的，可能是bug，我明天把你检查下

**Comment by itsnows** [comment]
可以的，小的安装包多大的，我明天抽空把你检查下。发自我的华为手机-------- 原始邮件 --------主题：Re: [itsnows/android-upgrade] 不可以下载比较小的安装包？？？？ (#1)发件人：strootree 收件人：itsnows/android-upgrade 抄送：Subscribed Closed #1.

**Comment by strootree** [comment]
两兆 改到7兆就可以了 不知道为什么 麻烦老哥了
